#  <author>Nasr Aldin</author>
#  <email>nasr2ldin@gmail.com</email>
#  <github>https://github.com/nasraldin/my-dev-containers</github>
#  <date>04/28/2021 01:03 AM</date>

FROM camunda/camunda-bpm-platform:latest

COPY ./camunda /camunda/lib
