#  <author>Nasr Aldin</author>
#  <email>nasr2ldin@gmail.com</email>
#  <github>https://github.com/nasraldin</github>
#  <date>05/10/2021 08:31 AM</date>

FROM atmoz/sftp

COPY ./sftp/users.conf /etc/sftp/users.conf:ro
# COPY ./.docker/ssh_keys /etc/ssh