#  <author>Nasr Aldin</author>
#  <email>nasr2ldin@gmail.com</email>
#  <github>https://github.com/nasraldin</github>
#  <date>05/10/2021 08:31 AM</date>

FROM rabbitmq:management

COPY ./rabbitmq /etc/rabbitmq

CMD ["rabbitmq-server"]